// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmqnx1WtEhPZ-thUoXAObN_i55lb6Dfgc',
    appId: '1:772774284221:web:a7b8642654297b004220d4',
    messagingSenderId: '772774284221',
    projectId: 'patria-dce7d',
    authDomain: 'patria-dce7d.firebaseapp.com',
    storageBucket: 'patria-dce7d.firebasestorage.app',
    measurementId: 'G-4YT1YBMLQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqTlXL_8kRtxE3hQndfAwnmte2Sma12Fw',
    appId: '1:789058511912:android:a460a6107ac32d60c3011d',
    messagingSenderId: '789058511912',
    projectId: 'patria-app-71f36',
    storageBucket: 'patria-app-71f36.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN5abs9DKEKYMwJzK59wDGfUw91KZeVLE',
    appId: '1:789058511912:ios:e0b3744abc34ff33c3011d',
    messagingSenderId: '789058511912',
    projectId: 'patria-app-71f36',
    storageBucket: 'patria-app-71f36.firebasestorage.app',
    androidClientId: '789058511912-sm9p3q8morh5672qthbnbd54el13gcud.apps.googleusercontent.com',
    iosClientId: '789058511912-s8ait6j5rlpsgrtlan4m5auaos1v4kao.apps.googleusercontent.com',
    iosBundleId: 'com.cloudiasolutions.patria',
  );
}
