// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmqnx1WtEhPZ-thUoXAObN_i55lb6Dfgc',
    appId: '1:772774284221:web:a7b8642654297b004220d4',
    messagingSenderId: '772774284221',
    projectId: 'patria-dce7d',
    authDomain: 'patria-dce7d.firebaseapp.com',
    storageBucket: 'patria-dce7d.firebasestorage.app',
    measurementId: 'G-4YT1YBMLQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5KDfR3nFWyE3TRMfI278_c9Lg8IBjfeI',
    appId: '1:772774284221:android:f7341644868110324220d4',
    messagingSenderId: '772774284221',
    projectId: 'patria-dce7d',
    storageBucket: 'patria-dce7d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW3nnV0zFI4SNojhgOstxpkC2CB1Ogsac',
    appId: '1:772774284221:ios:3408c33bf119cba94220d4',
    messagingSenderId: '772774284221',
    projectId: 'patria-dce7d',
    storageBucket: 'patria-dce7d.firebasestorage.app',
    androidClientId: '772774284221-bcqssiof86bhp1iakcukkghc5vd46ntr.apps.googleusercontent.com',
    iosClientId: '772774284221-s3bnl8ant2cc8fvtneeqpaqf4vnjhggf.apps.googleusercontent.com',
    iosBundleId: 'com.cloudiasolutions.patria',
  );
}
